name: CoinGecko Assets
run-name: "CoinGecko top assets"

on:
  workflow_dispatch:
  schedule:
    - cron: '15 */12 * * *'

permissions:
  contents: write

concurrency:
  group: coingecko
  cancel-in-progress: false

jobs:
  top:
    uses: ./.github/workflows/download-assets.yml
    with:
      source: coingecko
      mode: top
    secrets: inherit
