name: Download CoinGecko Trending Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours

jobs:
  download-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout core repository
      uses: actions/checkout@v2
      with:
        repository: gemwalletcom/core
        path: core

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Run img-downloader
      run: cargo run --package img-downloader -- --folder ../blockchains --coin-list trending --delay 20000
      working-directory: core
  
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add . ':!core'
        if git diff --cached --quiet; then
          echo "Nothing to commit (excluding core/)"
        else
          git commit -m "Update CoinGecko trending assets images"
          git push
        fi
      
